sudo: required
cache:
  packages: true
  apt: true
  directories:
    - $HOME/.ya

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libc6-dev
      - python-dev
      - python3-dev
      - g++-6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update -qq ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install -qq g++-5 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90 ; fi

before_script: |
    # `ya` provides it's own compiler toolchains, `CC` and CXX` environment variables will override
    # them so we have to unset them.
    #
    unset CC
    unset CXX
    # export PYCURL_SSL_LIBRARY=openssl
    # pip install webdavclient || sudo pip2 install webdavclient

matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      env: CB_BUILD_AGENT='clang-linux-x86_64-release-cuda'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env: CB_BUILD_AGENT='python2-linux-x86_64-release'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
    - os: linux
      dist: trusty
      language: python
      python: 3.5
      env: CB_BUILD_AGENT='python35-linux-x86_64-release'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
    - os: linux
      dist: trusty
      language: python
      python: 3.4
      env: CB_BUILD_AGENT='python34-linux-x86_64-release'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
    - os: linux
      dist: trusty
      language: python
      python: 3.6
      env: CB_BUILD_AGENT='python36-linux-x86_64-release'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
    - os: osx
      osx_image: xcode8.3
      language: cpp
      env: CB_BUILD_AGENT='clang-darwin-x86_64-release'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
    - os: osx
      osx_image: xcode8.3
      language: cpp
      env: CB_BUILD_AGENT='R-clang-darwin-x86_64-release'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
    - os: linux
      dist: trusty
      language: cpp
      env: CB_BUILD_AGENT='R-clang-linux-x86_64-release'
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh

